In [31]:
import pandas as pd
from item.historical.scripts.util.managers.dataframe import DataframeManager
from item.historical.scripts.util.managers.dataframe import ColumnName
from item.historical.scripts.util.managers.country_code import CountryCodeManager
from item.common import paths

# Variables used all over the notebook

In [32]:
DATASET_ID = "T001"
dataframeManager = DataframeManager(DATASET_ID)
countryCodeManager = CountryCodeManager()

# Creating the dataframe and viewing the data

In [33]:
# Creating a dataframe from the csv data
path = paths['data']/'historical'/'input'/'T001_input.csv'
df = pd.read_csv(path)
df

,COUNTRY,Country,VARIABLE,Variable,YEAR,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1995,1995,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10369.0,NaN,NaN
1,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1996,1996,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10166.0,NaN,NaN
2,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1997,1997,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10735.0,NaN,NaN
3,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1998,1998,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,13420.0,NaN,NaN
4,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1999,1999,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,14144.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574,CZE,Czech Republic,T-SEA-CAB,Coastal shipping (national transport),2014,2014,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,NaN,M,Missing value; data cannot exist
1575,CZE,Czech Republic,T-SEA-CAB,Coastal shipping (national transport),2015,2015,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,NaN,M,Missing value; data cannot exist
1576,CZE,Czech Republic,T-SEA-CAB,Coastal shipping (national transport),2016,2016,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,NaN,M,Missing value; data cannot exist
1577,CZE,Czech Republic,T-SEA-CAB,Coastal shipping (national transport),2017,2017,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,NaN,M,Missing value; data cannot exist
1578,CZE,Czech Republic,T-SEA-CAB,Coastal shipping (national transport),2018,2018,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,NaN,M,Missing value; data cannot exist

# Removing all unnecessary columns

### Rule: To comply with the latest template, we will drop all the unnecessary columns and rename others.

In [34]:
# Droping the repeated columns
columns_to_delete = ["COUNTRY", "YEAR", "VARIABLE","Reference Period Code","Unit Code","Reference Period", "Flag Codes", "Flags", "PowerCode Code"]
df.drop(columns=columns_to_delete, inplace = True)
df

,Country,Variable,Year,Unit,PowerCode,Value
0,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...
1574,Czech Republic,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,NaN
1575,Czech Republic,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,NaN
1576,Czech Republic,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,NaN
1577,Czech Republic,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,NaN
1578,Czech Republic,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,NaN

## Getting a generic idea of what countries are missing values and dropping NaN values
    Rule: Erase all value with NaN

In [35]:
list_of_countries_with_missing_values = list(set(df[df['Value'].isnull()]["Country"]))
print(">> Number of countries missing values: {}".format(len(list_of_countries_with_missing_values)))
print(">> Countries missing values:")
print(list_of_countries_with_missing_values)
print(">> Number of rows to erase: {}".format(len(df[df['Value'].isnull()])))

>> Number of countries missing values: 16
>> Countries missing values:
['Greece', 'Hungary', 'Slovak Republic', 'Switzerland', 'Serbia, Republic of', 'Czech Republic', 'Liechtenstein', 'North Macedonia', 'Belarus', 'Austria', 'Montenegro, Republic of', 'Moldova', 'Armenia', 'Slovenia', 'Luxembourg', 'Lithuania']
>> Number of rows to erase: 750

In [36]:
# Dropping the values
df.dropna(inplace = True)

# Adding the "Source Column"
    Rule: Add the same source to all rows since all data comes from same source

In [37]:
dataframeManager.simple_column_insert(df,ColumnName.SOURCE.value,"International Transport Forum")
df

,Source,Country,Variable,Year,Unit,PowerCode,Value
0,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...,...
1428,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0
1429,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0
1430,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0
1431,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0
1432,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0

# Adding the "Service" column
    Rule: Since all the data is associated to "Freight," the Service is "Freight"

In [38]:
dataframeManager.simple_column_insert(df,ColumnName.SERVICE.value,"Freight")
df

,Service,Source,Country,Variable,Year,Unit,PowerCode,Value
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0

# Adding the "Technology" and "Fuel" columns
    Rule: The dataset does not provide any data about those two columns, so we added the default value of "All" in both cases.

In [39]:
dataframeManager.simple_column_insert(df,ColumnName.TECHNOLOGY.value,"All")
dataframeManager.simple_column_insert(df,ColumnName.FUEL.value,"All")
df

,Fuel,Technology,Service,Source,Country,Variable,Year,Unit,PowerCode,Value
0,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...,...,...,...,...
1428,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0
1429,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0
1430,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0
1431,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0
1432,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0

# Setting the correct unit name in the "Unit" column
    Rule: Based on the template, the correct unit for "Fraight Activity" is "10^9 tonne-km / yr", so we will assign those units to the data

In [40]:
# Dropping the current "Unit" column
df.drop(columns=["Unit"], inplace = True)

# Adding the new "Unit" column
df[ColumnName.UNIT.value] = ["10^9 tonne-km / yr"]*len(df) 
df

,Fuel,Technology,Service,Source,Country,Variable,Year,PowerCode,Value,Unit
0,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Millions,10369.0,10^9 tonne-km / yr
1,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Millions,10166.0,10^9 tonne-km / yr
2,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Millions,10735.0,10^9 tonne-km / yr
3,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Millions,13420.0,10^9 tonne-km / yr
4,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Millions,14144.0,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...,...
1428,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Millions,18553.0,10^9 tonne-km / yr
1429,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Millions,19189.0,10^9 tonne-km / yr
1430,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Millions,19492.0,10^9 tonne-km / yr
1431,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Millions,22087.0,10^9 tonne-km / yr
1432,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Millions,21779.0,10^9 tonne-km / yr

# Setting the correct magnitude of the "Value" column
    Rule: The current data is in million. We will convert all values to billions. In which (1M = 0.001B)

In [41]:
# Removing the "PowerCode" column since it is not necessary
df.drop(columns=["PowerCode"], inplace = True)

# Looping though each row and convert each value to billion magnitude
for index, row in df.iterrows():
    current_value = row.Value
    new_value = current_value * float(0.001)
    df.Value[index] = new_value
df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Fuel,Technology,Service,Source,Country,Variable,Year,Value,Unit
0,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,10^9 tonne-km / yr
1,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,10^9 tonne-km / yr
2,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,10^9 tonne-km / yr
3,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,10^9 tonne-km / yr
4,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...
1428,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,10^9 tonne-km / yr
1429,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,10^9 tonne-km / yr
1430,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,10^9 tonne-km / yr
1431,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,10^9 tonne-km / yr
1432,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,10^9 tonne-km / yr

# Adding the "Mode" column
    Rule: Since all the data is about shipping, all rows have "Shipping" as mode

In [42]:
dataframeManager.simple_column_insert(df,ColumnName.MODE.value,"Shipping")
df

,Mode,Fuel,Technology,Service,Source,Country,Variable,Year,Value,Unit
0,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,10^9 tonne-km / yr
1,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,10^9 tonne-km / yr
2,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,10^9 tonne-km / yr
3,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,10^9 tonne-km / yr
4,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...,...
1428,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,10^9 tonne-km / yr
1429,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,10^9 tonne-km / yr
1430,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,10^9 tonne-km / yr
1431,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,10^9 tonne-km / yr
1432,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,10^9 tonne-km / yr

# Adding the column "Vehicle Type" 
    Rule: Since all the data in this dataset is associted to coastal shipping, the vehicle type is "Coastal"

In [43]:
dataframeManager.simple_column_insert(df,ColumnName.VEHICLE_TYPE.value,"Coastal")
df

,Vehicle Type,Mode,Fuel,Technology,Service,Source,Country,Variable,Year,Value,Unit
0,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,10^9 tonne-km / yr
1,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,10^9 tonne-km / yr
2,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,10^9 tonne-km / yr
3,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,10^9 tonne-km / yr
4,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...,...,...
1428,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,10^9 tonne-km / yr
1429,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,10^9 tonne-km / yr
1430,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,10^9 tonne-km / yr
1431,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,10^9 tonne-km / yr
1432,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,10^9 tonne-km / yr

# Renaming the column "Variable"
    Rule: There is only one activity being perform in this dataset and that is the "Freight Activity". We are setting, for each row, the variable "Freight Activity"

In [44]:
# Dropping the current "Variable" column
df.drop(columns=["Variable"], inplace = True)

# Adding the new "Variable" column with the new data
dataframeManager.simple_column_insert(df,ColumnName.VARIABLE.value,"Freight Activity")
df

,Variable,Vehicle Type,Mode,Fuel,Technology,Service,Source,Country,Year,Value,Unit
0,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1995,10.369,10^9 tonne-km / yr
1,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1996,10.166,10^9 tonne-km / yr
2,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1997,10.735,10^9 tonne-km / yr
3,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1998,13.420,10^9 tonne-km / yr
4,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1999,14.144,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...,...,...
1428,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2014,18.553,10^9 tonne-km / yr
1429,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2015,19.189,10^9 tonne-km / yr
1430,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2016,19.492,10^9 tonne-km / yr
1431,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2017,22.087,10^9 tonne-km / yr
1432,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2018,21.779,10^9 tonne-km / yr

# Getting the ISO code for each country
    Rule: For each country, we need to assign their respective ISO Code

## Determining which countries do not appear in the list of ISO Code
    As seen from the code below, four countries appear to not have ISO code. However, the reason is because the countries are written in a format that is not understandable. So, this is how each those "missing" countries will be called in order to obtain their ISO code
    
    Original Name --> New name
        > Montenegro, Republic of --> Montenegro
        > Korea --> Korea, Republic of
        > Serbia, Republic of --> Serbia

In [45]:
# Getting the list of countries available
list_of_countries = list(set(df["Country"]))

# Getting the list of countries with no ISO code
countries_with_no_ISO_code = countryCodeManager.get_list_of_countries_with_no_iso_code(list_of_countries)
        
# Print this list of countries with no ISO codes
countries_with_no_ISO_code

['Korea']

## Adding the ISO column to the df

In [46]:
dirty_list_of_all_countries = df["Country"]
clean_list_of_all_countries = []

for country in dirty_list_of_all_countries:
    if country == "Montenegro, Republic of":
        clean_list_of_all_countries.append("Montenegro")
    elif country == "Bosnia-Herzegovina":
        clean_list_of_all_countries.append("Bosnia and Herzegovina")
    elif country == "Korea":
        clean_list_of_all_countries.append("Korea, Republic of")
    elif country == "Serbia, Republic of":
        clean_list_of_all_countries.append("Serbia")
    else:
        clean_list_of_all_countries.append(country)

# Ensure the size of the cleaned list is the same as the dirty list
assert len(clean_list_of_all_countries) == len(dirty_list_of_all_countries)

# Assert that for all elements in the new list, no country is left without an ISO code
assert len(countryCodeManager.get_list_of_countries_with_no_iso_code(clean_list_of_all_countries)) == 0

# Getting the list of iso codes
list_of_iso_codes = countryCodeManager.get_list_of_iso_for_countries(clean_list_of_all_countries)

# Adding the column to the dataframe
df[ColumnName.ISO_CODE.value] = list_of_iso_codes
df

,Variable,Vehicle Type,Mode,Fuel,Technology,Service,Source,Country,Year,Value,Unit,ISO Code
0,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1995,10.369,10^9 tonne-km / yr,CAN
1,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1996,10.166,10^9 tonne-km / yr,CAN
2,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1997,10.735,10^9 tonne-km / yr,CAN
3,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1998,13.420,10^9 tonne-km / yr,CAN
4,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1999,14.144,10^9 tonne-km / yr,CAN
...,...,...,...,...,...,...,...,...,...,...,...,...
1428,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2014,18.553,10^9 tonne-km / yr,TUR
1429,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2015,19.189,10^9 tonne-km / yr,TUR
1430,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2016,19.492,10^9 tonne-km / yr,TUR
1431,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2017,22.087,10^9 tonne-km / yr,TUR
1432,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2018,21.779,10^9 tonne-km / yr,TUR

# Getting the ITEM region for each country
    Rule: For each country, we need to assign an ITEM region

## Determining which countries are missing an ITEM region
    As seen from the cell below, there is no country that does no have a respective ITEM region. Therefore, no further cleaning needs to be done to get the item regions.

In [47]:
# Getting the list of ISO codes
list_of_iso_codes = list(set(df["ISO Code"]))

# Getting the list of ISO code with no region
iso_code_with_no_region = countryCodeManager.get_list_of_iso_codes_with_no_region(list_of_iso_codes)

# printing the list of ISO codes
iso_code_with_no_region

[]

## Adding the ITEM region column to the dataset

In [48]:
# Getting the complete list of iso codes
list_of_all_codes = df["ISO Code"]

item_region = countryCodeManager.get_list_of_regions_for_iso_codes(list_of_all_codes)

# Adding the column to the dataframe
df[ColumnName.ITEM_REGION.value] = item_region
df

,Variable,Vehicle Type,Mode,Fuel,Technology,Service,Source,Country,Year,Value,Unit,ISO Code,Region
0,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1995,10.369,10^9 tonne-km / yr,CAN,Canada
1,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1996,10.166,10^9 tonne-km / yr,CAN,Canada
2,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1997,10.735,10^9 tonne-km / yr,CAN,Canada
3,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1998,13.420,10^9 tonne-km / yr,CAN,Canada
4,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Canada,1999,14.144,10^9 tonne-km / yr,CAN,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2014,18.553,10^9 tonne-km / yr,TUR,Non-EU Europe
1429,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2015,19.189,10^9 tonne-km / yr,TUR,Non-EU Europe
1430,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2016,19.492,10^9 tonne-km / yr,TUR,Non-EU Europe
1431,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2017,22.087,10^9 tonne-km / yr,TUR,Non-EU Europe
1432,Freight Activity,Coastal,Shipping,All,All,Freight,International Transport Forum,Turkey,2018,21.779,10^9 tonne-km / yr,TUR,Non-EU Europe

# Reordering the columns
    Rule: The columns should follow the order established in the latest template

In [49]:
df = dataframeManager.reorder_columns(df)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,Fuel,Value,Year
0,International Transport Forum,Canada,CAN,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.369,1995
1,International Transport Forum,Canada,CAN,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.166,1996
2,International Transport Forum,Canada,CAN,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.735,1997
3,International Transport Forum,Canada,CAN,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,13.420,1998
4,International Transport Forum,Canada,CAN,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,14.144,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,International Transport Forum,Turkey,TUR,Non-EU Europe,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,18.553,2014
1429,International Transport Forum,Turkey,TUR,Non-EU Europe,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,19.189,2015
1430,International Transport Forum,Turkey,TUR,Non-EU Europe,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,19.492,2016
1431,International Transport Forum,Turkey,TUR,Non-EU Europe,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,22.087,2017
1432,International Transport Forum,Turkey,TUR,Non-EU Europe,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,21.779,2018

# Exporting results

In [31]:
# Programming Friendly View
dataframeManager.create_programming_friendly_file(df)

# User Friendly View
dataframeManager.create_user_friendly_file(df)

> PF File saved at: /Users/hlinero/Documents/database/item/historical/scripts
> UF File saved at: /Users/hlinero/Documents/database/item/historical/scripts